export { default as Header } from './Header'
export { default as Opening } from './Opening'
export { default as Grid } from './Grid'
export { default as Skills } from './Skills'
export { default as Works } from './Works'
export { default as Contacts } from './Contacts'
export { default as Quote } from './Quote'
export { default as Footer } from './Footer'
export { default as MobileMenu } from './MobileMenu'
export { ContactButton } from './Contacts/ContactButton.jsx'
export { default as SEO } from './SEO.jsx'
